networks:
  
  database:
    name: database
    driver: bridge
  hackathon:
    name: hackathon
    driver: bridge


services:
      
  database:
    image: "postgres:16-alpine"
    container_name: postgresql
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hackathon
      PGDATA: /var/lib/postgresql/data/pgdata
      
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

    ports:
      - "5433:5432"

    networks:
      - database
      - hackathon

  hr_director:
    image: "hackathon/hr_director:latest"
    container_name: hr_director

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.HRDirectorService/Dockerfile

    environment:
      - EMPLOYEES_NUM=10
      
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8083/api/hr_director/health || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s

    depends_on:
      database:
        condition: service_healthy

    networks:
      - database
      - hackathon
        
  hr_manager:
    image: "hackathon/hr_manager:latest"
    container_name: hr_manager
    
    build:
      context: .
      dockerfile: EveryoneToTheHackathon.HRManagerService/Dockerfile
    
    environment:
      - EMPLOYEES_NUM=10
      
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8082/api/hr_manager/health || exit 1" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
      
    depends_on:
      hr_director:
        condition: service_healthy
    
    networks:
      - hackathon
        
  teamlead-1:
    image: "hackathon/employee:latest"
    container_name: teamlead-1
    
    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile
      
    environment:
      - ID=1
      - TITLE=TeamLead
      - NAME=Филиппова Ульяна
    
    depends_on:
      hr_manager:
        condition: service_healthy
    
    networks:
      - hackathon

  teamlead-2:
    image: "hackathon/employee:latest"
    container_name: teamlead-2

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile

    environment:
      - ID=2
      - TITLE=TeamLead
      - NAME=Николаев Григорий

    depends_on:
      hr_manager:
        condition: service_healthy

    networks:
      - hackathon

  teamlead-3:
    image: "hackathon/employee:latest"
    container_name: teamlead-3

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile

    environment:
      - ID=3
      - TITLE=TeamLead
      - NAME=Андреева Вероника

    depends_on:
      hr_manager:
        condition: service_healthy

    networks:
      - hackathon

  teamlead-4:
    image: "hackathon/employee:latest"
    container_name: teamlead-4

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile

    environment:
      - ID=4
      - TITLE=TeamLead
      - NAME=Коротков Михаил

    depends_on:
      hr_manager:
        condition: service_healthy

    networks:
      - hackathon

  teamlead-5:
    image: "hackathon/employee:latest"
    container_name: teamlead-5

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile

    environment:
      - ID=5
      - TITLE=TeamLead
      - NAME=Кузнецов Александр

    depends_on:
      hr_manager:
        condition: service_healthy

    networks:
      - hackathon

  junior-1:
    image: "hackathon/employee:latest"
    container_name: junior-1

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile

    environment:
      - ID=1
      - TITLE=Junior
      - NAME=Юдин Адам

    depends_on:
      hr_manager:
        condition: service_healthy

    networks:
      - hackathon

  junior-2:
    image: "hackathon/employee:latest"
    container_name: junior-2

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile

    environment:
      - ID=2
      - TITLE=Junior
      - NAME=Яшина Яна

    depends_on:
      hr_manager:
        condition: service_healthy

    networks:
      - hackathon

  junior-3:
    image: "hackathon/employee:latest"
    container_name: junior-3

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile

    environment:
      - ID=3
      - TITLE=Junior
      - NAME=Никитина Вероника

    depends_on:
      hr_manager:
        condition: service_healthy

    networks:
      - hackathon

  junior-4:
    image: "hackathon/employee:latest"
    container_name: junior-4

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile

    environment:
      - ID=4
      - TITLE=Junior
      - NAME=Рябинин Александр

    depends_on:
      hr_manager:
        condition: service_healthy

    networks:
      - hackathon

  junior-5:
    image: "hackathon/employee:latest"
    container_name: junior-5

    build:
      context: .
      dockerfile: EveryoneToTheHackathon.EmployeeService/Dockerfile

    environment:
      - ID=5
      - TITLE=Junior
      - NAME=Ильин Тимофей

    depends_on:
      hr_manager:
        condition: service_healthy

    networks:
      - hackathon